name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.2'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Mocha Report
        if: always()  
        uses: actions/upload-artifact@v3
        with:
          name: mocha-report
          path: cypress/reports 
        
         
